version: "3.9"
services:
  backend:
    image: ghcr.io/ashizius/film-react-nest_backend:latest
    build:
      context: ./backend # директория сборки (контекст)
    container_name: backend
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
    restart: always
#    ports:
#      - "3000:3000"
    depends_on:
      - postgres
    healthcheck:
      test: "wget -nv -t1 --spider 'http://localhost:3000/'"
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - internal


  frontend:
    image: ghcr.io/ashizius/film-react-nest_frontend:latest
    build:
      context: ./frontend # директория сборки (контекст)
    container_name: frontend
    env_file:
      - ./frontend/.env
    volumes:
      - frontendvol:/var/www/app/dist:rw

  postgres:
    image: "postgres:16"
    container_name: postgres
    restart: always
#    ports:
#      - "5432:5432"
#      - 8080:8080
#      - 8081:80
    env_file:
      - ./.env
    volumes:
      # монтируем директорию ./pg-data основной ОС в директорию с данными в контейнере
      - ./pg-data:/var/lib/postgresql/data/pgdata
    networks:
      - internal

  server:
    #image: ghcr.io/ashizius/film-react-nest_nginx:latest
    image: nginx:alpine
    container_name: server
    build:
      context: ./nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - internal
      - internet
    restart: always
    volumes:
      - frontendvol:/var/www/app/frontend:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend/public:/var/www/app/public:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/letsencrypt/:ro
    depends_on:
      - frontend
#      - certbot



  certbot:
    image: certbot/certbot:latest
    networks:
      - internal
      - internet
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

volumes:
  frontendvol:

networks:
  default:
    internal: true
  internal:
    internal: true
    driver: bridge
  internet:
    driver: bridge
